# Generated by Django 4.0.3 on 2023-07-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binvo',
            name='href',
            field=models.CharField(default='#', max_length=100, unique=True),
        ),
    ]
