# Generated by Django 4.0.3 on 2023-07-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_binvo_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='model_name',
            new_name='brand_name',
        ),
    ]
