# Generated by Django 4.0.3 on 2023-07-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0003_rename_model_name_shoe_brand_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binvo',
            options={'ordering': ['closet_name', 'bin_number'], 'verbose_name': 'Bin', 'verbose_name_plural': 'Bins'},
        ),
        migrations.AlterModelOptions(
            name='shoe',
            options={'ordering': ['bin', 'brand_name'], 'verbose_name': 'Shoe', 'verbose_name_plural': 'Shoes'},
        ),
    ]
