# Generated by Django 4.0.3 on 2023-07-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0004_alter_binvo_options_alter_shoe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoe',
            options={'ordering': ['bin', 'model'], 'verbose_name': 'Shoe', 'verbose_name_plural': 'Shoes'},
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='brand_name',
            new_name='model',
        ),
    ]
